go_import_path: github.com/kevinburke/go-html-boilerplate

language: go

go:
  - 1.7
  - 1.8
  - tip

before_script:
    - go get -u ./...

script:
    - make race-test
    - make diff
    - make bench
